FROM python:3.8-alpine


ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /flask_app

COPY ./requirements.txt .
RUN pip install -r requirements.txt
EXPOSE 5000

COPY . .