version: "3"

services:

  postgresql_container:
    image: postgres
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
   
volumes:
  db_data: